
export const UNKNOWN_MODE = -1;
export const DREAM_MODE_NUMBER = 1;

export const ANIMATION_MODE_METEOR = 205;
export const ANIMATION_MODE_BREATHING = 206;
export const ANIMATION_MODE_STACK = 207;
export const ANIMATION_MODE_FLOW = 208;
export const ANIMATION_MODE_WAVE = 209;
export const ANIMATION_MODE_FLASH = 210;
export const ANIMATION_MODE_STATIC = 211;
export const ANIMATION_MODE_CATCHUP = 212;

export const CUSTOM_EFFECT_1 = 1;
export const CUSTOM_EFFECT_2 = 2;
export const CUSTOM_EFFECT_3 = 3;
export const CUSTOM_EFFECT_4 = 4;
export const CUSTOM_EFFECT_5 = 5;
export const CUSTOM_EFFECT_6 = 6;
export const CUSTOM_EFFECT_7 = 7;
export const CUSTOM_EFFECT_8 = 8;
export const CUSTOM_EFFECT_9 = 9;
export const CUSTOM_EFFECT_10 = 10;
export const CUSTOM_EFFECT_11 = 11;
export const CUSTOM_EFFECT_12 = 12;

// Preset Effects
export const PRESET_EFFECT_RAINBOW = 0;
export const PRESET_EFFECT_COLORS_CHANGING_METEORS = 1;
export const PRESET_EFFECT_FLOWING_COLORS = 2;
export const PRESET_EFFECT_OVERLAYING_FLOWING = 3;
export const PRESET_EFFECT_RED_STACKING = 4;
export const PRESET_EFFECT_GREEN_STACKING = 5;
export const PRESET_EFFECT_BLUE_STACKING = 6;
export const PRESET_EFFECT_COLORS_CHANGING_STACKING = 7;
export const PRESET_EFFECT_FADING_FLOWING = 8;
export const PRESET_EFFECT_COLOR_CHANGING_CROSS_FLOWING = 9;
export const PRESET_EFFECT_CROSS_FLOWING = 10;
export const PRESET_EFFECT_CHASING_COLOR_DOTS = 11;
export const PRESET_EFFECT_COLORFUL_WAVE = 12;
export const PRESET_EFFECT_BURNING_FIRE = 13;
export const PRESET_EFFECT_RED_METEOR = 14;
export const PRESET_EFFECT_GREEN_METEOR = 15;
export const PRESET_EFFECT_BLUE_METEOR = 16;
export const PRESET_EFFECT_YELLOW_METEOR = 17;
export const PRESET_EFFECT_CYAN_METEOR = 18;
export const PRESET_EFFECT_PURPLE_METEOR = 19;
export const PRESET_EFFECT_WHITE_METEOR = 20;
export const PRESET_EFFECT_RED_WAVE = 21;
export const PRESET_EFFECT_GREEN_WAVE = 22;
export const PRESET_EFFECT_BLUE_WAVE = 23;
export const PRESET_EFFECT_YELLOW_WAVE = 24;
export const PRESET_EFFECT_CYAN_WAVE = 25;
export const PRESET_EFFECT_PURPLE_WAVE = 26;
export const PRESET_EFFECT_WHITE_WAVE = 27;
export const PRESET_EFFECT_RED_CHASING_DOTS = 28;
export const PRESET_EFFECT_GREEN_CHASING_DOTS = 29;
export const PRESET_EFFECT_BLUE_CHASING_DOTS = 30;
export const PRESET_EFFECT_YELLOW_CHASING_DOTS = 31;
export const PRESET_EFFECT_CYAN_CHASING_DOTS = 32;
export const PRESET_EFFECT_WHITE_CHASING_DOTS = 33;
export const PRESET_EFFECT_PURPLE_CHASING_DOTS = 34;
export const PRESET_EFFECT_CYAN_DOTS_BLINK_ON_SILVER = 35;
export const PRESET_EFFECT_PURPLE_DOTS_BLINK_ON_SILVER = 36;
export const PRESET_EFFECT_YELLOW_DOTS_BLINK_ON_SILVER = 37;
export const PRESET_EFFECT_BLUE_DOTS_BLINK_ON_SILVER = 38;
export const PRESET_EFFECT_GREEN_DOTS_BLINK_ON_SILVER = 39;
export const PRESET_EFFECT_RED_DOTS_BLINK_ON_SILVER = 40;
export const PRESET_EFFECT_RED_AND_GREEN_FLOWING = 41;
export const PRESET_EFFECT_RED_AND_BLUE_FLOWING = 42;
export const PRESET_EFFECT_RED_AND_YELLOW_FLOWING = 43;
export const PRESET_EFFECT_RED_AND_CYAN_FLOWING = 44;
export const PRESET_EFFECT_RED_AND_PURPLE_FLOWING = 45;
export const PRESET_EFFECT_RED_AND_WHITE_FLOWING = 46;
export const PRESET_EFFECT_GREEN_AND_BLUE_FLOWING = 47;
export const PRESET_EFFECT_GREEN_AND_YELLOW_FLOWING = 48;
export const PRESET_EFFECT_GREEN_AND_CYAN_FLOWING = 49;
export const PRESET_EFFECT_GREEN_AND_PURPLE_FLOWING = 50;
export const PRESET_EFFECT_GREEN_AND_WHITE_FLOWING = 51;
export const PRESET_EFFECT_BLUE_AND_YELLOW_FLOWING = 52;
export const PRESET_EFFECT_BLUE_AND_CYAN_FLOWING = 53;
export const PRESET_EFFECT_BLUE_AND_PURPLE_FLOWING = 54;
export const PRESET_EFFECT_BLUE_AND_WHITE_FLOWING = 55;
export const PRESET_EFFECT_YELLOW_AND_CYAN_FLOWING = 56;
export const PRESET_EFFECT_YELLOW_AND_PURPLE_FLOWING = 57;
export const PRESET_EFFECT_YELLOW_AND_WHITE_FLOWING = 58;
export const PRESET_EFFECT_CYAN_AND_PURPLE_FLOWING = 59;
export const PRESET_EFFECT_CYAN_AND_WHITE_FLOWING = 60;
export const PRESET_EFFECT_RED_CROSSING_FLOWING = 61;
export const PRESET_EFFECT_GREEN_CROSSING_FLOWING = 62;
export const PRESET_EFFECT_BLUE_CROSSING_FLOWING = 63;
export const PRESET_EFFECT_YELLOW_CROSSING_FLOWING = 64;
export const PRESET_EFFECT_CYAN_CROSSING_FLOWING = 65;
export const PRESET_EFFECT_PURPLE_CROSSING_FLOWING = 66;
export const PRESET_EFFECT_WHITE_CROSSING_FLOWING = 67;
export const PRESET_EFFECT_RED_ARROWS = 68;
export const PRESET_EFFECT_GREEN_ARROWS = 69;
export const PRESET_EFFECT_BLUE_ARROWS = 70;
export const PRESET_EFFECT_YELLOW_ARROWS = 71;
export const PRESET_EFFECT_CYAN_ARROWS = 72;
export const PRESET_EFFECT_PURPLE_ARROWS = 73;
export const PRESET_EFFECT_RED_CUDGEL = 74;
export const PRESET_EFFECT_GREEN_CUDGEL = 75;
export const PRESET_EFFECT_BLUE_CUDGEL = 76;
export const PRESET_EFFECT_YELLOW_CUDGEL = 77;
export const PRESET_EFFECT_CYAN_CUDGEL = 78;
export const PRESET_EFFECT_PURPLE_CUDGEL = 79;
export const PRESET_EFFECT_GAPS_IN_CYAN = 80;
export const PRESET_EFFECT_GAPS_IN_PURPLE = 81;
export const PRESET_EFFECT_GAPS_IN_YELLOW = 82;
export const PRESET_EFFECT_GAPS_IN_BLUE = 83;
export const PRESET_EFFECT_GAPS_IN_GREEN = 84;
export const PRESET_EFFECT_GAPS_IN_RED = 85;
export const PRESET_EFFECT_RED_BREATHE = 86;
export const PRESET_EFFECT_GREEN_BREATHE = 87;
export const PRESET_EFFECT_BLUE_BREATHE = 88;
export const PRESET_EFFECT_YELLOW_BREATHE = 89;
export const PRESET_EFFECT_CYAN_BREATHE = 90;
export const PRESET_EFFECT_PURPLE_BREATHE = 91;
export const PRESET_EFFECT_WHITE_BREATHE = 92;
export const PRESET_EFFECT_RED_ARROWS_REVERSE = 93;
export const PRESET_EFFECT_GREEN_ARROWS_REVERSE = 94;
export const PRESET_EFFECT_BLUE_ARROWS_REVERSE = 95;
export const PRESET_EFFECT_YELLOW_ARROWS_REVERSE = 96;
export const PRESET_EFFECT_CYAN_ARROWS_REVERSE = 97;
export const PRESET_EFFECT_PURPLE_ARROWS_REVERSE = 98;
export const PRESET_EFFECT_RED_DOTS_RUNNING_IN_CYAN = 99;
export const PRESET_EFFECT_GREEN_DOTS_RUNNING_IN_PURPLE = 100;
export const PRESET_EFFECT_BLUE_DOTS_RUNNING_IN_YELLOW = 101;
export const PRESET_EFFECT_YELLOW_DOTS_RUNNING_IN_BLUE = 102;
export const PRESET_EFFECT_CYAN_DOTS_RUNNING_IN_GREEN = 103;
export const PRESET_EFFECT_PURPLE_DOTS_RUNNING_IN_RED = 104;
export const PRESET_EFFECT_WHITE_DOTS_RUNNING_IN_CYAN = 105;
export const PRESET_EFFECT_RED_FADING_IN_AND_OUT = 106;
export const PRESET_EFFECT_GREEN_FADING_IN_AND_OUT = 107;
export const PRESET_EFFECT_BLUE_FADING_IN_AND_OUT = 108;
export const PRESET_EFFECT_YELLOW_FADING_IN_AND_OUT = 109;
export const PRESET_EFFECT_CYAN_FADING_IN_AND_OUT = 110;
export const PRESET_EFFECT_PURPLE_FADING_IN_AND_OUT = 111;
export const PRESET_EFFECT_WHITE_FADING_IN_AND_OUT = 112;
export const PRESET_EFFECT_RED_METEOR_REVERSE = 113;
export const PRESET_EFFECT_GREEN_METEOR_REVERSE = 114;
export const PRESET_EFFECT_BLUE_METEOR_REVERSE = 115;
export const PRESET_EFFECT_YELLOW_METEOR_REVERSE = 116;
export const PRESET_EFFECT_CYAN_METEOR_REVERSE = 117;
export const PRESET_EFFECT_PURPLE_METEOR_REVERSE = 118;
export const PRESET_EFFECT_WHITE_METEOR_REVERSE = 119;
export const PRESET_EFFECT_RED_WAVE_2 = 120;
export const PRESET_EFFECT_GREEN_WAVE_2 = 121;
export const PRESET_EFFECT_BLUE_WAVE_2 = 122;
export const PRESET_EFFECT_YELLOW_WAVE_2 = 123;
export const PRESET_EFFECT_CYAN_WAVE_2 = 124;
export const PRESET_EFFECT_PURPLE_WAVE_2 = 125;
export const PRESET_EFFECT_WHITE_WAVE_2 = 126;
export const PRESET_EFFECT_RED_WING_DOTS = 127;
export const PRESET_EFFECT_GREEN_SWING_DOTS = 128;
export const PRESET_EFFECT_BLUE_SWING_DOTS = 129;
export const PRESET_EFFECT_YELLOW_SWING_DOTS = 130;
export const PRESET_EFFECT_CYAN_SWING_DOTS = 131;
export const PRESET_EFFECT_PURPLE_SWING_DOTS = 132;
export const PRESET_EFFECT_WHITE_SWING_DOTS = 133;
export const PRESET_EFFECT_RED_AND_GREEN_CUDGEL = 134;
export const PRESET_EFFECT_GREEN_AND_BLUE_CUDGEL = 135;
export const PRESET_EFFECT_BLUE_AND_YELLOW_CUDGEL = 136;
export const PRESET_EFFECT_YELLOW_AND_CYAN_CUDGEL = 137;
export const PRESET_EFFECT_CYAN_AND_PURPLE_CUDGEL = 138;
export const PRESET_EFFECT_PURPLE_AND_WHITE_CUDGEL = 139;
export const PRESET_EFFECT_WHITE_AND_RED_CUDGEL = 140;
export const PRESET_EFFECT_RED_OVERLAPS_GREEN = 141;
export const PRESET_EFFECT_GREEN_OVERLAPS_RED = 142;
export const PRESET_EFFECT_BLUE_OVERLAPS_GREEN = 143;
export const PRESET_EFFECT_YELLOW_OVERLAPS_GREEN = 144;
export const PRESET_EFFECT_CYAN_OVERLAPS_GREEN = 145;
export const PRESET_EFFECT_PURPLE_OVERLAPS_GREEN = 146;
export const PRESET_EFFECT_WHITE_OVERLAPS_GREEN = 147;
export const PRESET_EFFECT_RED_OVERLAPS_BLUE = 148;
export const PRESET_EFFECT_GREEN_OVERLAPS_BLUE = 149;
export const PRESET_EFFECT_BLUE_OVERLAPS_GREEN_2 = 150;
export const PRESET_EFFECT_YELLOW_OVERLAPS_BLUE = 151;
export const PRESET_EFFECT_CYAN_OVERLAPS_BLUE = 152;
export const PRESET_EFFECT_PURPLE_OVERLAPS_BLUE = 153;
export const PRESET_EFFECT_WHITE_OVERLAPS_BLUE = 154;
export const PRESET_EFFECT_PINK_MIX_BLUE = 155;
export const PRESET_EFFECT_GREEN_MIX_YELLOW = 156;
export const PRESET_EFFECT_BLUE_MIX_PINK = 157;
export const PRESET_EFFECT_BLUE_MIX_WHITE = 158;
export const PRESET_EFFECT_GREEN_MIX_ORANGE = 159;
export const PRESET_EFFECT_BLUE_MIX_PURPLE = 160;
export const PRESET_EFFECT_CYAN_MIX_WHITE = 161;
export const PRESET_EFFECT_GREEN_BLINKING = 163;
export const PRESET_EFFECT_BLUE_BLINKING = 164;
export const PRESET_EFFECT_YELLOW_BLINKING = 165;
export const PRESET_EFFECT_CYAN_BLINKING = 166;
export const PRESET_EFFECT_PURPLE_BLINKING = 167;
export const PRESET_EFFECT_WHITE_BLINKING = 168;
export const PRESET_EFFECT_RED_STACKING_INTO_GREEN = 169;
export const PRESET_EFFECT_GREEN_STACKING_INTO_BLUE = 170;
export const PRESET_EFFECT_BLUE_STACKING_INTO_YELLOW = 171;
export const PRESET_EFFECT_YELLOW_STACKING_INTO_CYAN = 172;
export const PRESET_EFFECT_CYAN_STACKING_INTO_PURPLE = 173;
export const PRESET_EFFECT_PURPLE_STACKING_INTO_WHITE = 174;
export const PRESET_EFFECT_WHITE_STACKING_INTO_RED = 175;
export const PRESET_EFFECT_COLOR_CHANGING_BREATHING = 176;
export const PRESET_EFFECT_MULTICOLORED_GRADIENTS = 177;
export const PRESET_EFFECT_COLOR_FLASHING = 178;
export const PRESET_EFFECT_RAINBOW_REVERSE = 179;

export const ANIMATION_MODES = {
  [ANIMATION_MODE_STATIC]: 'STATIC',
  [ANIMATION_MODE_METEOR]: 'METEOR',
  [ANIMATION_MODE_BREATHING]: 'BREATHING',
  [ANIMATION_MODE_WAVE]: 'WAVE',
  [ANIMATION_MODE_CATCHUP]: 'CATCHUP',
  [ANIMATION_MODE_STACK]: 'STACK',
  [ANIMATION_MODE_FLASH]: 'FLASH',
  [ANIMATION_MODE_FLOW]: 'FLOW',
};

export const PRESET_EFFECTS = {
  [PRESET_EFFECT_RAINBOW]: 'Rainbow',
  [PRESET_EFFECT_COLORS_CHANGING_METEORS]: 'Colors changing meteors',
  [PRESET_EFFECT_FLOWING_COLORS]: 'Flowing Colors',
  [PRESET_EFFECT_OVERLAYING_FLOWING]: 'Overlaying Flowing',
  [PRESET_EFFECT_RED_STACKING]: 'Red stacking',
  [PRESET_EFFECT_GREEN_STACKING]: 'Green stacking',
  [PRESET_EFFECT_BLUE_STACKING]: 'Blue stacking',
  [PRESET_EFFECT_COLORS_CHANGING_STACKING]: 'Colors changing stacking',
  [PRESET_EFFECT_FADING_FLOWING]: 'Fading flowing',
  [PRESET_EFFECT_COLOR_CHANGING_CROSS_FLOWING]: 'Color changing cross flowing',
  [PRESET_EFFECT_CROSS_FLOWING]: 'Cross flowing',
  [PRESET_EFFECT_CHASING_COLOR_DOTS]: 'Chasing color dots',
  [PRESET_EFFECT_COLORFUL_WAVE]: 'Colorful wave',
  [PRESET_EFFECT_BURNING_FIRE]: 'Burning fire',
  [PRESET_EFFECT_RED_METEOR]: 'Red meteor',
  [PRESET_EFFECT_GREEN_METEOR]: 'Green meteor',
  [PRESET_EFFECT_BLUE_METEOR]: 'Blue meteor',
  [PRESET_EFFECT_YELLOW_METEOR]: 'Yellow meteor',
  [PRESET_EFFECT_CYAN_METEOR]: 'Cyan meteor',
  [PRESET_EFFECT_PURPLE_METEOR]: 'Purple meteor',
  [PRESET_EFFECT_WHITE_METEOR]: 'White meteor',
  [PRESET_EFFECT_RED_WAVE]: 'Red wave',
  [PRESET_EFFECT_GREEN_WAVE]: 'Green wave',
  [PRESET_EFFECT_BLUE_WAVE]: 'Blue wave',
  [PRESET_EFFECT_YELLOW_WAVE]: 'Yellow wave',
  [PRESET_EFFECT_CYAN_WAVE]: 'Cyan wave',
  [PRESET_EFFECT_PURPLE_WAVE]: 'Purple wave',
  [PRESET_EFFECT_WHITE_WAVE]: 'White wave',
  [PRESET_EFFECT_RED_CHASING_DOTS]: 'Red chasing dots',
  [PRESET_EFFECT_GREEN_CHASING_DOTS]: 'Green chasing dots',
  [PRESET_EFFECT_BLUE_CHASING_DOTS]: 'Blue chasing dots',
  [PRESET_EFFECT_YELLOW_CHASING_DOTS]: 'Yellow chasing dots',
  [PRESET_EFFECT_CYAN_CHASING_DOTS]: 'Cyan chasing dots',
  [PRESET_EFFECT_WHITE_CHASING_DOTS]: 'White chasing dots',
  [PRESET_EFFECT_PURPLE_CHASING_DOTS]: 'Purple chasing dots',
  [PRESET_EFFECT_CYAN_DOTS_BLINK_ON_SILVER]: 'Cyan dots blink on silver',
  [PRESET_EFFECT_PURPLE_DOTS_BLINK_ON_SILVER]: 'Purple dots blink on silver',
  [PRESET_EFFECT_YELLOW_DOTS_BLINK_ON_SILVER]: 'Yellow dots blink on silver',
  [PRESET_EFFECT_BLUE_DOTS_BLINK_ON_SILVER]: 'Blue dots blink on silver',
  [PRESET_EFFECT_GREEN_DOTS_BLINK_ON_SILVER]: 'Green dots blink on silver',
  [PRESET_EFFECT_RED_DOTS_BLINK_ON_SILVER]: 'Red dots blink on silver',
  [PRESET_EFFECT_RED_AND_GREEN_FLOWING]: 'Red and Green flowing',
  [PRESET_EFFECT_RED_AND_BLUE_FLOWING]: 'Red and blue flowing',
  [PRESET_EFFECT_RED_AND_YELLOW_FLOWING]: 'Red and yellow flowing',
  [PRESET_EFFECT_RED_AND_CYAN_FLOWING]: 'Red and cyan flowing',
  [PRESET_EFFECT_RED_AND_PURPLE_FLOWING]: 'Red and purple flowing',
  [PRESET_EFFECT_RED_AND_WHITE_FLOWING]: 'Red and white flowing',
  [PRESET_EFFECT_GREEN_AND_BLUE_FLOWING]: 'Green and blue flowing',
  [PRESET_EFFECT_GREEN_AND_YELLOW_FLOWING]: 'Green and yellow flowing',
  [PRESET_EFFECT_GREEN_AND_CYAN_FLOWING]: 'Green and cyan flowing',
  [PRESET_EFFECT_GREEN_AND_PURPLE_FLOWING]: 'Green and purple flowing',
  [PRESET_EFFECT_GREEN_AND_WHITE_FLOWING]: 'Green and white flowing',
  [PRESET_EFFECT_BLUE_AND_YELLOW_FLOWING]: 'Blue and yellow flowing',
  [PRESET_EFFECT_BLUE_AND_CYAN_FLOWING]: 'Blue and cyan flowing',
  [PRESET_EFFECT_BLUE_AND_PURPLE_FLOWING]: 'Blue and purple flowing',
  [PRESET_EFFECT_BLUE_AND_WHITE_FLOWING]: 'Blue and white flowing',
  [PRESET_EFFECT_YELLOW_AND_CYAN_FLOWING]: 'Yellow and cyan flowing',
  [PRESET_EFFECT_YELLOW_AND_PURPLE_FLOWING]: 'Yellow and purple flowing',
  [PRESET_EFFECT_YELLOW_AND_WHITE_FLOWING]: 'Yellow and white flowing',
  [PRESET_EFFECT_CYAN_AND_PURPLE_FLOWING]: 'Cyan and purple flowing',
  [PRESET_EFFECT_CYAN_AND_WHITE_FLOWING]: 'Cyan and white flowing',
  [PRESET_EFFECT_RED_CROSSING_FLOWING]: 'Red crossing flowing',
  [PRESET_EFFECT_GREEN_CROSSING_FLOWING]: 'Green crossing flowing',
  [PRESET_EFFECT_BLUE_CROSSING_FLOWING]: 'Blue crossing flowing',
  [PRESET_EFFECT_YELLOW_CROSSING_FLOWING]: 'Yellow crossing flowing',
  [PRESET_EFFECT_CYAN_CROSSING_FLOWING]: 'Cyan crossing flowing',
  [PRESET_EFFECT_PURPLE_CROSSING_FLOWING]: 'Purple crossing flowing',
  [PRESET_EFFECT_WHITE_CROSSING_FLOWING]: 'White crossing flowing',
  [PRESET_EFFECT_RED_ARROWS]: 'Red arrows',
  [PRESET_EFFECT_GREEN_ARROWS]: 'Green arrows',
  [PRESET_EFFECT_BLUE_ARROWS]: 'Blue arrows',
  [PRESET_EFFECT_YELLOW_ARROWS]: 'Yellow arrows',
  [PRESET_EFFECT_CYAN_ARROWS]: 'Cyan arrows',
  [PRESET_EFFECT_PURPLE_ARROWS]: 'Purple arrows',
  [PRESET_EFFECT_RED_CUDGEL]: 'Red cudgel',
  [PRESET_EFFECT_GREEN_CUDGEL]: 'Green cudgel',
  [PRESET_EFFECT_BLUE_CUDGEL]: 'Blue cudgel',
  [PRESET_EFFECT_YELLOW_CUDGEL]: 'Yellow cudgel',
  [PRESET_EFFECT_CYAN_CUDGEL]: 'Cyan cudgel',
  [PRESET_EFFECT_PURPLE_CUDGEL]: 'Purple cudgel',
  [PRESET_EFFECT_GAPS_IN_CYAN]: 'Gaps in cyan',
  [PRESET_EFFECT_GAPS_IN_PURPLE]: 'Gaps in purple',
  [PRESET_EFFECT_GAPS_IN_YELLOW]: 'Gaps in yellow',
  [PRESET_EFFECT_GAPS_IN_BLUE]: 'Gaps in blue',
  [PRESET_EFFECT_GAPS_IN_GREEN]: 'Gaps in green',
  [PRESET_EFFECT_GAPS_IN_RED]: 'Gaps in red',
  [PRESET_EFFECT_RED_BREATHE]: 'Red breathe',
  [PRESET_EFFECT_GREEN_BREATHE]: 'Green breathe',
  [PRESET_EFFECT_BLUE_BREATHE]: 'Blue breathe',
  [PRESET_EFFECT_YELLOW_BREATHE]: 'Yellow breathe',
  [PRESET_EFFECT_CYAN_BREATHE]: 'Cyan breathe',
  [PRESET_EFFECT_PURPLE_BREATHE]: 'Purple breathe',
  [PRESET_EFFECT_WHITE_BREATHE]: 'White breathe',
  [PRESET_EFFECT_RED_ARROWS_REVERSE]: 'Red arrows reverse',
  [PRESET_EFFECT_GREEN_ARROWS_REVERSE]: 'Green arrows reverse',
  [PRESET_EFFECT_BLUE_ARROWS_REVERSE]: 'Blue arrows reverse',
  [PRESET_EFFECT_YELLOW_ARROWS_REVERSE]: 'Yellow arrows reverse',
  [PRESET_EFFECT_CYAN_ARROWS_REVERSE]: 'Cyan arrows reverse',
  [PRESET_EFFECT_PURPLE_ARROWS_REVERSE]: 'Purple arrows reverse',
  [PRESET_EFFECT_RED_DOTS_RUNNING_IN_CYAN]: 'Red dots running in cyan',
  [PRESET_EFFECT_GREEN_DOTS_RUNNING_IN_PURPLE]: 'Green dots running in purple',
  [PRESET_EFFECT_BLUE_DOTS_RUNNING_IN_YELLOW]: 'Blue dots running in yellow',
  [PRESET_EFFECT_YELLOW_DOTS_RUNNING_IN_BLUE]: 'Yellow dots running in blue',
  [PRESET_EFFECT_CYAN_DOTS_RUNNING_IN_GREEN]: 'Cyan dots running in green',
  [PRESET_EFFECT_PURPLE_DOTS_RUNNING_IN_RED]: 'Purple dots running in red',
  [PRESET_EFFECT_WHITE_DOTS_RUNNING_IN_CYAN]: 'White dots running in cyan',
  [PRESET_EFFECT_RED_FADING_IN_AND_OUT]: 'Red fading in and out',
  [PRESET_EFFECT_GREEN_FADING_IN_AND_OUT]: 'Green fading in and out',
  [PRESET_EFFECT_BLUE_FADING_IN_AND_OUT]: 'Blue fading in and out',
  [PRESET_EFFECT_YELLOW_FADING_IN_AND_OUT]: 'Yellow fading in and out',
  [PRESET_EFFECT_CYAN_FADING_IN_AND_OUT]: 'Cyan fading in and out',
  [PRESET_EFFECT_PURPLE_FADING_IN_AND_OUT]: 'Purple fading in and out',
  [PRESET_EFFECT_WHITE_FADING_IN_AND_OUT]: 'White fading in and out',
  [PRESET_EFFECT_RED_METEOR_REVERSE]: 'Red meteor reverse',
  [PRESET_EFFECT_GREEN_METEOR_REVERSE]: 'Green meteor reverse',
  [PRESET_EFFECT_BLUE_METEOR_REVERSE]: 'Blue meteor reverse',
  [PRESET_EFFECT_YELLOW_METEOR_REVERSE]: 'Yellow meteor reverse',
  [PRESET_EFFECT_CYAN_METEOR_REVERSE]: 'Cyan meteor reverse',
  [PRESET_EFFECT_PURPLE_METEOR_REVERSE]: 'Purple meteor reverse',
  [PRESET_EFFECT_WHITE_METEOR_REVERSE]: 'White meteor reverse',
  [PRESET_EFFECT_RED_WAVE_2]: 'Red wave 2',
  [PRESET_EFFECT_GREEN_WAVE_2]: 'Green wave 2',
  [PRESET_EFFECT_BLUE_WAVE_2]: 'Blue wave 2',
  [PRESET_EFFECT_YELLOW_WAVE_2]: 'Yellow wave 2',
  [PRESET_EFFECT_CYAN_WAVE_2]: 'Cyan wave 2',
  [PRESET_EFFECT_PURPLE_WAVE_2]: 'Purple wave 2',
  [PRESET_EFFECT_WHITE_WAVE_2]: 'White wave 2',
  [PRESET_EFFECT_RED_WING_DOTS]: 'Red wing dots',
  [PRESET_EFFECT_GREEN_SWING_DOTS]: 'Green swing dots',
  [PRESET_EFFECT_BLUE_SWING_DOTS]: 'Blue swing dots',
  [PRESET_EFFECT_YELLOW_SWING_DOTS]: 'Yellow swing dots',
  [PRESET_EFFECT_CYAN_SWING_DOTS]: 'Cyan swing dots',
  [PRESET_EFFECT_PURPLE_SWING_DOTS]: 'Purple swing dots',
  [PRESET_EFFECT_WHITE_SWING_DOTS]: 'White swing dots',
  [PRESET_EFFECT_RED_AND_GREEN_CUDGEL]: 'Red and green cudgel',
  [PRESET_EFFECT_GREEN_AND_BLUE_CUDGEL]: 'Green and blue cudgel',
  [PRESET_EFFECT_BLUE_AND_YELLOW_CUDGEL]: 'Blue and yellow cudgel',
  [PRESET_EFFECT_YELLOW_AND_CYAN_CUDGEL]: 'Yellow and cyan cudgel',
  [PRESET_EFFECT_CYAN_AND_PURPLE_CUDGEL]: 'Cyan and purple cudgel',
  [PRESET_EFFECT_PURPLE_AND_WHITE_CUDGEL]: 'Purple and white cudgel',
  [PRESET_EFFECT_WHITE_AND_RED_CUDGEL]: 'White and red cudgel',
  [PRESET_EFFECT_RED_OVERLAPS_GREEN]: 'Red overlaps green',
  [PRESET_EFFECT_GREEN_OVERLAPS_RED]: 'Green overlaps red',
  [PRESET_EFFECT_BLUE_OVERLAPS_GREEN]: 'Blue overlaps green',
  [PRESET_EFFECT_YELLOW_OVERLAPS_GREEN]: 'Yellow overlaps green',
  [PRESET_EFFECT_CYAN_OVERLAPS_GREEN]: 'Cyan overlaps green',
  [PRESET_EFFECT_PURPLE_OVERLAPS_GREEN]: 'Purple overlaps green',
  [PRESET_EFFECT_WHITE_OVERLAPS_GREEN]: 'White overlaps green',
  [PRESET_EFFECT_RED_OVERLAPS_BLUE]: 'Red overlaps blue',
  [PRESET_EFFECT_GREEN_OVERLAPS_BLUE]: 'Green overlaps blue',
  [PRESET_EFFECT_BLUE_OVERLAPS_GREEN_2]: 'Blue overlaps green 2',
  [PRESET_EFFECT_YELLOW_OVERLAPS_BLUE]: 'Yellow overlaps blue',
  [PRESET_EFFECT_CYAN_OVERLAPS_BLUE]: 'Cyan overlaps blue',
  [PRESET_EFFECT_PURPLE_OVERLAPS_BLUE]: 'Purple overlaps blue',
  [PRESET_EFFECT_WHITE_OVERLAPS_BLUE]: 'White overlaps blue',
  [PRESET_EFFECT_PINK_MIX_BLUE]: 'Pink mix blue',
  [PRESET_EFFECT_GREEN_MIX_YELLOW]: 'Green mix yellow',
  [PRESET_EFFECT_BLUE_MIX_PINK]: 'Blue mix pink',
  [PRESET_EFFECT_BLUE_MIX_WHITE]: 'Blue mix white',
  [PRESET_EFFECT_GREEN_MIX_ORANGE]: 'Green mix orange',
  [PRESET_EFFECT_BLUE_MIX_PURPLE]: 'Blue mix purple',
  [PRESET_EFFECT_CYAN_MIX_WHITE]: 'Cyan mix white',
  [PRESET_EFFECT_GREEN_BLINKING]: 'Green blinking',
  [PRESET_EFFECT_BLUE_BLINKING]: 'Blue blinking',
  [PRESET_EFFECT_YELLOW_BLINKING]: 'Yellow blinking',
  [PRESET_EFFECT_CYAN_BLINKING]: 'Cyan blinking',
  [PRESET_EFFECT_PURPLE_BLINKING]: 'Purple blinking',
  [PRESET_EFFECT_WHITE_BLINKING]: 'White blinking',
  [PRESET_EFFECT_RED_STACKING_INTO_GREEN]: 'Red stacking into green',
  [PRESET_EFFECT_GREEN_STACKING_INTO_BLUE]: 'Green stacking into blue',
  [PRESET_EFFECT_BLUE_STACKING_INTO_YELLOW]: 'Blue stacking into yellow',
  [PRESET_EFFECT_YELLOW_STACKING_INTO_CYAN]: 'Yellow stacking into cyan',
  [PRESET_EFFECT_CYAN_STACKING_INTO_PURPLE]: 'Cyan stacking into purple',
  [PRESET_EFFECT_PURPLE_STACKING_INTO_WHITE]: 'Purple stacking into white',
  [PRESET_EFFECT_WHITE_STACKING_INTO_RED]: 'White stacking into red',
  [PRESET_EFFECT_COLOR_CHANGING_BREATHING]: 'Color changing breathing',
  [PRESET_EFFECT_MULTICOLORED_GRADIENTS]: 'Multicolored gradients',
  [PRESET_EFFECT_COLOR_FLASHING]: 'Color Flashing',
  [PRESET_EFFECT_RAINBOW_REVERSE]: 'Rainbow reverse',
};

export const ALL_ANIMATION_MODES = {
  ...PRESET_EFFECTS,
  ...ANIMATION_MODES,
};

export const CUSTOM_EFFECTS = {
  'Custom Effect 1': CUSTOM_EFFECT_1,
  'Custom Effect 2': CUSTOM_EFFECT_2,
  'Custom Effect 3': CUSTOM_EFFECT_3,
  'Custom Effect 4': CUSTOM_EFFECT_4,
  'Custom Effect 5': CUSTOM_EFFECT_5,
  'Custom Effect 6': CUSTOM_EFFECT_6,
  'Custom Effect 7': CUSTOM_EFFECT_7,
  'Custom Effect 8': CUSTOM_EFFECT_8,
  'Custom Effect 9': CUSTOM_EFFECT_9,
  'Custom Effect 10': CUSTOM_EFFECT_10,
  'Custom Effect 11': CUSTOM_EFFECT_11,
  'Custom Effect 12': CUSTOM_EFFECT_12,
};
